spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://postgres:5432/flowiq
spring.datasource.username=flowiq
spring.datasource.password=flowiq123

spring.jpa.show-sql=false

logging.level.org.hibernate.SQL=WARN
