package com.flowiq.forecasts.provider;

import com.flowiq.forecasts.dto.ForecastInsightDto;
import com.flowiq.forecasts.engine.MonthlyFinancialData;

import java.math.BigDecimal;
import java.util.List;

/**
 * Extension point for AI-powered forecast insights.
 * Rule-based insights are generated by {@link RuleBasedForecastProvider};
 * future integrations (OpenAI, Claude, Gemini) can implement this interface as Spring beans.
 */
public interface ForecastProvider {

    List<ForecastInsightDto> generateInsights(ForecastContext context);

    record ForecastContext(
            boolean ukrainian,
            List<MonthlyFinancialData> historical,
            List<MonthlyFinancialData> projected,
            double revenueTrendPercent,
            double expenseTrendPercent,
            double profitTrendPercent,
            BigDecimal currentAnnualIncome,
            BigDecimal incomeLimit,
            double fopLimitUsagePercent,
            int monthsUntilFopLimit,
            BigDecimal currentTaxBurden,
            BigDecimal projectedTaxBurden,
            double taxTrendPercent,
            int fopGroup
    ) {}
}
