CREATE TABLE knowledge_articles (
    id           BIGSERIAL PRIMARY KEY,
    slug         VARCHAR(120)  NOT NULL UNIQUE,
    title_uk     VARCHAR(255)  NOT NULL,
    title_en     VARCHAR(255)  NOT NULL,
    category     VARCHAR(30)   NOT NULL,
    content_uk   TEXT          NOT NULL,
    content_en   TEXT          NOT NULL,
    summary_uk   VARCHAR(500),
    summary_en   VARCHAR(500),
    impact_uk    VARCHAR(500),
    impact_en    VARCHAR(500),
    tags_uk      VARCHAR(500),
    tags_en      VARCHAR(500),
    published_at DATE,
    view_count   INTEGER       NOT NULL DEFAULT 0,
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_knowledge_articles_category ON knowledge_articles (category);
CREATE INDEX idx_knowledge_articles_updated_at ON knowledge_articles (updated_at DESC);
CREATE INDEX idx_knowledge_articles_published_at ON knowledge_articles (published_at DESC);

INSERT INTO knowledge_articles (slug, title_uk, title_en, category, content_uk, content_en, summary_uk, summary_en, tags_uk, tags_en, published_at, view_count) VALUES
('fop-group-1-overview',
 'Група ФОП 1: умови та податки',
 'FOP Group 1: Conditions and Taxes',
 'FOP_GROUPS',
 'Група 1 спрощеної системи оподаткування призначена для ФОП без працівників із річним доходом до 1 672 000 грн (2025). Дозволені види діяльності: роздрібна торгівля, побутові послуги, дрібне виробництво. Єдиний податок: 1% для торгівлі або 2% для послуг. ЄСВ сплачується щомісяця незалежно від доходу. ПДВ та податок на доходи фізичних осіб не сплачуються за умови дотримання ліміту та дозволених КВЕДів.',
 'Group 1 of the simplified tax system is for sole proprietors without employees and annual income up to UAH 1,672,000 (2025). Allowed activities include retail trade, household services, and small-scale production. Unified tax: 1% for trade or 2% for services. ESV is paid monthly regardless of income. VAT and personal income tax do not apply when limits and permitted KVED codes are respected.',
 'Група 1 — найпростіший режим для ФОП без працівників з лімітом до 1,67 млн грн на рік.',
 'Group 1 is the simplest regime for sole proprietors without employees, capped at UAH 1.67M per year.',
 'ФОП 1 група,єдиний податок,ліміт доходу,без працівників',
 'FOP group 1,unified tax,income limit,no employees',
 '2025-01-01', 42),

('fop-group-2-overview',
 'Група ФОП 2: IT-фрілансери та послуги',
 'FOP Group 2: IT Freelancers and Services',
 'FOP_GROUPS',
 'Група 2 — найпопулярніший режим для IT, консалтингу та сервісного бізнесу. Річний ліміт доходу: 5 328 000 грн. Дозволено до 10 працівників. Ставка єдиного податку: 3% (без ПДВ) або 5% (з ПДВ). ФОП сплачує ЄСВ щомісяця. Квартальна декларація подається до 40 днів після кварталу. При перевищенні ліміту необхідно перейти на групу 3 або загальну систему.',
 'Group 2 is the most popular regime for IT, consulting, and service businesses. Annual income limit: UAH 5,328,000. Up to 10 employees allowed. Unified tax rate: 3% (without VAT) or 5% (with VAT). ESV is paid monthly. Quarterly declaration is due within 40 days after the quarter. Exceeding the limit requires transition to Group 3 or the general tax system.',
 'Група 2 підходить для IT та консалтингу з лімітом 5,3 млн грн і до 10 працівників.',
 'Group 2 suits IT and consulting with a UAH 5.3M limit and up to 10 employees.',
 'ФОП 2 група,IT,єдиний податок 3%,єдиний податок 5%,10 працівників',
 'FOP group 2,IT,unified tax 3%,unified tax 5%,10 employees',
 '2025-01-01', 128),

('fop-group-3-overview',
 'Група ФОП 3: масштабування бізнесу',
 'FOP Group 3: Scaling Your Business',
 'FOP_GROUPS',
 'Група 3 призначена для ФОП із вищим обсягом доходу — до 7 818 000 грн на рік. Кількість працівників не обмежена. Єдиний податок: 5% від доходу. ФОП 3 групи зобов''язані бути платниками ПДВ (20%) та подавати декларацію з ПДВ щомісяця. Також сплачується ЄСВ. Ця група оптимальна для зростаючого бізнесу, який перевищив ліміти групи 2.',
 'Group 3 is for sole proprietors with higher revenue — up to UAH 7,818,000 per year. Employee count is unlimited. Unified tax: 5% of income. Group 3 FOPs must register as VAT payers (20%) and file monthly VAT returns. ESV also applies. This group suits growing businesses that exceeded Group 2 limits.',
 'Група 3 — для бізнесу з доходом до 7,8 млн грн, обов''язковий ПДВ та єдиний податок 5%.',
 'Group 3 is for businesses up to UAH 7.8M revenue, with mandatory VAT and 5% unified tax.',
 'ФОП 3 група,ПДВ,єдиний податок 5%,масштабування',
 'FOP group 3,VAT,unified tax 5%,scaling',
 '2025-01-01', 96),

('fop-general-tax-system',
 'Загальна система оподаткування для ФОП',
 'General Tax System for FOP',
 'FOP_GROUPS',
 'Загальна система застосовується при перевищенні лімітів спрощеної системи, заборонених видах діяльності або добровільному переході. ФОП сплачує податок на доходи фізичних осіб 18%, військовий збір 5%, ПДВ 20% (якщо є платником), ЄСВ. Облік ведеться за правилами, ближчими до юридичних осіб. Потрібна повна звітність та детальний облік доходів і витрат.',
 'The general tax system applies when simplified system limits are exceeded, for prohibited activities, or by voluntary transition. FOP pays 18% personal income tax, 5% military tax, 20% VAT (if registered), and ESV. Accounting follows rules closer to legal entities. Full reporting and detailed income/expense records are required.',
 'Загальна система — ПДФО 18%, військовий збір, ПДВ та повний облік.',
 'General system includes 18% income tax, military tax, VAT, and full accounting.',
 'загальна система,ПДФО 18%,ПДВ,перехід',
 'general tax system,income tax 18%,VAT,transition',
 '2025-01-01', 35),

('unified-tax-guide',
 'Єдиний податок для ФОП: повний гід',
 'Unified Tax for FOP: Complete Guide',
 'TAXES',
 'Єдиний податок замінює ПДФО та ПДВ (для більшості ФОП на спрощеній системі). Ставки: 1–2% (група 1), 3–5% (група 2), 5% (група 3). Сплата — щоквартально до 20 числа місяця, наступного за звітним кварталом. Розрахунок: оподатковуваний дохід × ставка. Важливо вести Книгу обліку доходів. При зміні групи або ставки — подати заяву до ДПС.',
 'Unified tax replaces personal income tax and VAT (for most FOPs on the simplified system). Rates: 1–2% (group 1), 3–5% (group 2), 5% (group 3). Payment is quarterly by the 20th of the month following the reporting quarter. Calculation: taxable income × rate. An income ledger must be maintained. When changing group or rate, file an application with the tax authority.',
 'Єдиний податок сплачується щоквартально за ставкою залежно від групи ФОП.',
 'Unified tax is paid quarterly at a rate depending on the FOP group.',
 'єдиний податок,ставка,квартальна сплата,книга обліку',
 'unified tax,rate,quarterly payment,income ledger',
 '2025-01-01', 87),

('vat-for-fop-group-3',
 'ПДВ для ФОП 3 групи',
 'VAT for FOP Group 3',
 'TAXES',
 'ФОП 3 групи є платниками ПДВ зі ставкою 20%. Щомісяця подається декларація з ПДВ до 20 числа. ПДВ нараховується на постачання товарів і послуг, але можна відшкодувати вхідний ПДВ за рахунками постачальників. Важливо вести податкові накладні та реєстр. При роботі з B2B-клієнтами ПДВ-статус є обов''язковим.',
 'Group 3 FOPs are VAT payers at 20%. Monthly VAT return is due by the 20th. VAT is charged on goods and services supply, but input VAT can be credited from supplier invoices. Tax invoices and registers must be maintained. For B2B clients, VAT status is mandatory.',
 'ФОП 3 групи сплачують ПДВ 20% з щомісячною декларацією.',
 'Group 3 FOPs pay 20% VAT with a monthly declaration.',
 'ПДВ,20%,ФОП 3 група,декларація',
 'VAT,20%,FOP group 3,declaration',
 '2025-01-01', 54),

('esv-payment-rules',
 'ЄСВ для ФОП: правила сплати',
 'ESV for FOP: Payment Rules',
 'ESV',
 'Єдиний соціальний внесок (ЄСВ) — обов''язковий щомісячний платіж для пенсійного страхування. Мінімальна сума = мінімальна зарплата × 22%. Сплата до 19 числа наступного місяця. ЄСВ сплачується навіть у місяці без доходу для збереження страхового стажу. При доході вище мінімального ЄСВ може розраховуватися від фактичного доходу (залежно від групи та обраної бази).',
 'Unified social contribution (ESV) is a mandatory monthly payment for pension insurance. Minimum amount = minimum wage × 22%. Payment is due by the 19th of the following month. ESV is paid even in months with no income to preserve insurance record. If income exceeds the minimum, ESV may be calculated from actual income (depending on group and chosen base).',
 'ЄСВ сплачується щомісяця до 19 числа, мінімум 22% від мінімальної зарплати.',
 'ESV is paid monthly by the 19th, at minimum 22% of the minimum wage.',
 'ЄСВ,22%,мінімальна зарплата,страховий стаж',
 'ESV,22%,minimum wage,insurance record',
 '2025-01-01', 112),

('esv-minimum-amount-2026',
 'Мінімальний ЄСВ у 2026 році',
 'Minimum ESV in 2026',
 'ESV',
 'У 2026 році мінімальна зарплата встановлена на рівні, що впливає на мінімальний ЄСВ. ФОП повинні щомісяця перевіряти актуальну суму на сайті ДПС. Формула: мінімальна зарплата × 22%. Несплата або прострочення ЄСВ призводить до штрафів та втрати страхового стажу. Рекомендується налаштувати автоплатіж у банку.',
 'In 2026, the minimum wage level affects the minimum ESV amount. FOPs should verify the current amount monthly on the tax authority website. Formula: minimum wage × 22%. Non-payment or late ESV leads to penalties and loss of insurance record. Setting up a bank auto-payment is recommended.',
 'Мінімальний ЄСВ у 2026 залежить від мінімальної зарплати × 22%.',
 'Minimum ESV in 2026 depends on minimum wage × 22%.',
 'ЄСВ 2026,мінімальна зарплата,штрафи',
 'ESV 2026,minimum wage,penalties',
 '2026-01-01', 28),

('military-tax-fop',
 'Військовий збір для ФОП',
 'Military Tax for FOP',
 'MILITARY_TAX',
 'Військовий збір (5%) застосовується до доходів фізичних осіб на загальній системі. ФОП на єдиному податку (групи 1–3) зазвичай не сплачують військовий збір з бізнес-доходу. Виняток — доходи, що оподатковуються за правилами загальної системи, та виплати працівникам (утримання у джерела). Слідкуйте за законодавчими змінами щодо ставок та пільг.',
 'Military tax (5%) applies to personal income under the general tax system. FOPs on unified tax (groups 1–3) usually do not pay military tax on business income. Exceptions include income taxed under general rules and employee payments (withheld at source). Monitor legislative changes regarding rates and exemptions.',
 'ФОП на єдиному податку зазвичай не сплачують військовий збір з бізнес-доходу.',
 'FOPs on unified tax usually do not pay military tax on business income.',
 'військовий збір,5%,єдиний податок,утримання',
 'military tax,5%,unified tax,withholding',
 '2025-01-01', 67),

('quarterly-declaration-fop',
 'Квартальна декларація ФОП',
 'Quarterly FOP Declaration',
 'DECLARATIONS',
 'ФОП на спрощеній системі подають декларацію платника єдиного податку щоквартально. Термін: до 40 календарних днів після закінчення кварталу (для груп 1–3). У декларації відображається дохід за квартал, обрана ставка, сума єдиного податку до сплати. Подання — через кабінет платника ДПС. Зберігайте підтвердження подання та платіжні документи.',
 'FOPs on the simplified system file a unified tax payer declaration quarterly. Deadline: within 40 calendar days after quarter end (groups 1–3). The declaration shows quarterly income, chosen rate, and unified tax due. Filing is via the tax authority online cabinet. Keep filing confirmations and payment documents.',
 'Квартальна декларація подається до 40 днів після кварталу через кабінет ДПС.',
 'Quarterly declaration is filed within 40 days after the quarter via the tax cabinet.',
 'декларація,квартал,єдиний податок,ДПС',
 'declaration,quarter,unified tax,tax authority',
 '2025-01-01', 73),

('annual-declaration-fop',
 'Річна декларація ФОП',
 'Annual FOP Declaration',
 'DECLARATIONS',
 'Річна декларація про майновий стан і доходи подається до 1 травня року, наступного за звітним. ФОП на єдиному податку також подають річну декларацію єдиного податку. У декларації зазначаються усі джерела доходу, витрати (для загальної системи), суми сплачених податків. Рекомендується підготувати декларацію заздалегідь, перевіривши Книгу обліку доходів.',
 'Annual property and income declaration is due by May 1 of the year following the reporting year. Unified tax FOPs also file an annual unified tax declaration. The declaration lists all income sources, expenses (general system), and taxes paid. Prepare early by reconciling the income ledger.',
 'Річна декларація подається до 1 травня наступного року.',
 'Annual declaration is due by May 1 of the following year.',
 'річна декларація,1 травня,майновий стан',
 'annual declaration,May 1,property and income',
 '2025-01-01', 45),

('kved-overview',
 'КВЕД: що це і навіщо ФОП',
 'KVED: What It Is and Why FOP Needs It',
 'KVED_DIRECTORY',
 'КВЕД (Класифікатор видів економічної діяльності) — код, що описує вид діяльності ФОП. При реєстрації обирається основний КВЕД і додаткові. Код визначає дозволені операції, ставку єдиного податку (для групи 1) та можливість перебування на спрощеній системі. Зміна КВЕДів — через держреєстратор або ЦНАП. Неправильний КВЕД може призвести до штрафів.',
 'KVED (Classifier of Economic Activities) is a code describing the FOP activity type. Main and additional KVED codes are selected at registration. The code determines permitted operations, unified tax rate (group 1), and simplified system eligibility. KVED changes are made via the state registrar or ASC. Incorrect KVED may lead to penalties.',
 'КВЕД визначає вид діяльності ФОП та податкові умови.',
 'KVED defines FOP activity type and tax conditions.',
 'КВЕД,класифікатор,реєстрація,62.01',
 'KVED,classifier,registration,62.01',
 '2025-01-01', 58),

('popular-it-kveds',
 'Популярні IT-КВЕДи для ФОП',
 'Popular IT KVED Codes for FOP',
 'KVED_DIRECTORY',
 'Найпоширеніші КВЕДи для IT-ФОП: 62.01 — комп''ютерне програмування; 62.02 — консультування з інформатизації; 62.09 — інша діяльність у сфері ІТ; 63.11 — оброблення даних; 63.12 — веб-портали. Для дизайну: 74.10. Для консалтингу: 70.22. Обирайте КВЕДи, що відповідають фактичним договорам і рахункам.',
 'Most common IT KVED codes: 62.01 — computer programming; 62.02 — IT consulting; 62.09 — other IT activities; 63.11 — data processing; 63.12 — web portals. For design: 74.10. For consulting: 70.22. Choose KVED codes that match actual contracts and invoices.',
 'Топ IT-КВЕДи: 62.01, 62.02, 62.09, 63.11, 63.12.',
 'Top IT KVED codes: 62.01, 62.02, 62.09, 63.11, 63.12.',
 '62.01,62.02,62.09,IT,програмування',
 '62.01,62.02,62.09,IT,programming',
 '2025-01-01', 91),

('income-ledger-basics',
 'Книга обліку доходів для ФОП',
 'Income Ledger for FOP',
 'ACCOUNTING_BASICS',
 'Книга обліку доходів — обов''язковий документ для ФОП на спрощеній системі. Фіксує всі надходження на рахунки та готівку. Ведеться щоденно або при кожній операції. Зберігається 1095 днів. Може вестися в паперовому або електронному вигляді (з дотриманням вимог ДПС). Без книги — ризик штрафу при перевірці.',
 'The income ledger is mandatory for FOPs on the simplified system. It records all bank and cash receipts. Maintained daily or per transaction. Retained for 1095 days. May be paper or electronic (per tax authority requirements). Missing ledger risks penalties during audits.',
 'Книга обліку доходів обов''язкова для ФОП на спрощеній системі.',
 'Income ledger is mandatory for FOPs on the simplified system.',
 'книга обліку,доходи,облік,ДПС',
 'income ledger,revenue,accounting,tax authority',
 '2025-01-01', 39),

('expense-documentation',
 'Документування витрат ФОП',
 'Expense Documentation for FOP',
 'ACCOUNTING_BASICS',
 'На спрощеній системі витрати не зменшують єдиний податок, але їх документування важливе для управлінського обліку та загальної системи. Зберігайте рахунки, акти, договори, банківські виписки. Для загальної системи витрати повинні бути підтверджені первинними документами та пов''язані з діяльністю.',
 'On the simplified system, expenses do not reduce unified tax, but documentation matters for management accounting and the general system. Keep invoices, acts, contracts, bank statements. Under the general system, expenses must be supported by primary documents and related to business activity.',
 'Витрати документуються рахунками, актами та договорами.',
 'Expenses are documented with invoices, acts, and contracts.',
 'витрати,документи,рахунки,первинні документи',
 'expenses,documents,invoices,primary documents',
 '2025-01-01', 31),

('can-fop-hire-employees',
 'Чи може ФОП наймати працівників?',
 'Can FOP Hire Employees?',
 'BUSINESS_FAQ',
 'Група 1 — найм заборонений. Група 2 — до 10 працівників. Група 3 та загальна система — без обмежень. При наймі потрібно оформити трудовий договір, сплачувати ЄСВ та ПДФО з зарплати, подавати звітність 1ДФ. Перед наймом перевірте, чи ваша група це дозволяє.',
 'Group 1 — hiring prohibited. Group 2 — up to 10 employees. Group 3 and general system — no limit. Hiring requires employment contracts, ESV and income tax on salaries, and 1DF reporting. Verify your group allows hiring before signing contracts.',
 'Група 1 — без працівників; група 2 — до 10; група 3 — без ліміту.',
 'Group 1 — no employees; group 2 — up to 10; group 3 — unlimited.',
 'найм,працівники,трудовий договір,1ДФ',
 'hiring,employees,employment contract,1DF',
 '2025-01-01', 76),

('income-limit-exceeded',
 'Що робити при перевищенні ліміту доходу',
 'What to Do When Income Limit Is Exceeded',
 'BUSINESS_FAQ',
 'При перевищенні річного ліміту групи ФОП зобов''язаний перейти на вищу групу або загальну систему протягом 40 днів. Дохід понад ліміт оподатковується за правилами нової групи. Рекомендується моніторити дохід щомісяця, планувати перехід заздалегідь та консультуватися з бухгалтером.',
 'When the annual group income limit is exceeded, FOP must transition to a higher group or general system within 40 days. Income above the limit is taxed under the new group rules. Monitor income monthly, plan transitions early, and consult an accountant.',
 'Перевищення ліміту — перехід на вищу групу протягом 40 днів.',
 'Exceeding the limit requires transition to a higher group within 40 days.',
 'ліміт доходу,перехід,40 днів,перевищення',
 'income limit,transition,40 days,exceeded',
 '2025-01-01', 64),

('fop-group-3-taxes-faq',
 'Які податки платить ФОП 3 групи?',
 'What Taxes Does FOP Group 3 Pay?',
 'BUSINESS_FAQ',
 'ФОП 3 групи сплачує: 1) Єдиний податок — 5% від доходу (щоквартально); 2) ПДВ — 20% на постачання товарів/послуг (щомісячна декларація); 3) ЄСВ — щомісяця (мінімум 22% від мінімальної зарплати); 4) ПДФО та військовий збір — при виплаті зарплати працівникам (утримання). З бізнес-доходу військовий збір зазвичай не сплачується.',
 'FOP Group 3 pays: 1) Unified tax — 5% of income (quarterly); 2) VAT — 20% on goods/services supply (monthly return); 3) ESV — monthly (minimum 22% of minimum wage); 4) Income tax and military tax — when paying employee salaries (withheld). Military tax on business income usually does not apply.',
 'ФОП 3 групи: єдиний податок 5%, ПДВ 20%, ЄСВ щомісяця.',
 'FOP Group 3: 5% unified tax, 20% VAT, monthly ESV.',
 'ФОП 3 група,податки,єдиний податок,ПДВ,ЄСВ',
 'FOP group 3,taxes,unified tax,VAT,ESV',
 '2025-01-01', 156),

('legal-change-2025-tax-rates',
 'Зміни ставок єдиного податку у 2025 році',
 'Unified Tax Rate Changes in 2025',
 'LEGAL_CHANGES',
 'У 2025 році збережено структуру груп ФОП з оновленими лімітами доходу. Група 1: до 1 672 000 грн. Група 2: до 5 328 000 грн. Група 3: до 7 818 000 грн. Ставки єдиного податку без змін: 1–2%, 3–5%, 5%. Рекомендується перевірити актуальні ліміти на сайті ДПС на початку року.',
 'In 2025, the FOP group structure is maintained with updated income limits. Group 1: up to UAH 1,672,000. Group 2: up to UAH 5,328,000. Group 3: up to UAH 7,818,000. Unified tax rates unchanged: 1–2%, 3–5%, 5%. Verify current limits on the tax authority website at year start.',
 'Оновлені ліміти доходу для груп ФОП у 2025 році.',
 'Updated income limits for FOP groups in 2025.',
 '2025,ліміти,єдиний податок,законодавство',
 '2025,limits,unified tax,legislation',
 '2025-01-15', 44),

('legal-change-2026-minimum-wage',
 'Підвищення мінімальної зарплати у 2026 році',
 'Minimum Wage Increase in 2026',
 'LEGAL_CHANGES',
 'Підвищення мінімальної зарплати у 2026 році впливає на мінімальний ЄСВ для ФОП. ФОП повинні перерахувати щомісячний ЄСВ та оновити автоплатежі в банку. Також зростають витрати на зарплати працівників при їх наявності.',
 'The 2026 minimum wage increase affects minimum ESV for FOPs. FOPs must recalculate monthly ESV and update bank auto-payments. Employee salary costs also increase where applicable.',
 'Підвищення мінімальної зарплати збільшує мінімальний ЄСВ.',
 'Minimum wage increase raises minimum ESV.',
 '2026,мінімальна зарплата,ЄСВ,зміни',
 '2026,minimum wage,ESV,changes',
 '2026-01-01', 22);

UPDATE knowledge_articles SET
    impact_uk = 'ФОП повинні оновити фінансове планування та перевірити відповідність групи доходу.',
    impact_en = 'FOPs must update financial planning and verify group eligibility against income.'
WHERE category = 'LEGAL_CHANGES';
